<a href="https://colab.research.google.com/github/jaydengonzal2021/Statistics/blob/main/Jayden_Gonzalez_2023_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [2]:
for i in range(100): #this line generates a list of 100 numbers starting at 0
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [3]:
for i in range(5,8): #this line generatesd a list of numbers starting at 5 and ending before 8
    print(i)

5
6
7


In [4]:
for i in range(3): #this line generates a 3 number long lost like before but it also tells the system to put the words "test number" beforehand
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [5]:
def square(x): #this line defines a command "square" so the system knows when you put square and a avriable it will square the number
    return x**2

In [6]:
square(5) #example of square being used

25

In [7]:
square(square(2)) #example showing you cna use square twice in one line

16

In [8]:
square(square(square(2))) #example showing you can use square three times in one line


256

In [9]:
square(123456) #this shows it works on very large numberd

15241383936

In [10]:
square(square(5))

625

In [11]:
def add_two(x): #this line defines the command "add two" so the system knows to add 2 to the variable that this command is used with
    return x+2

In [12]:
add_two(5) #example of add two being used

7

In [13]:
square(add_two(5)) #example of add two and square being used together

49

### Logical Branching

In [14]:
choice = "apple" #this command sets your choice as the word apple

In [15]:
if choice == "apple": #this line tells the sytem that when you choose apple it should write out a certain response and also specifies a different response for different choices

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


In [16]:
choice = "orange" #this line chose orange like how apple was chosen first

In [17]:
if choice == "apple": #this line is repeated to show it works when you dont choose apples

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [18]:
choice = "apple" #this set your choise back to apples

In [19]:
if choice == "apple": #this block expands the response command from before to tell the sytem to respond with a longer message

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [20]:
choice = input("Please enter your choice (i.e. apple): ") 

Please enter your choice (i.e. apple): 


In [21]:
choice

''

In [80]:
if choice == "apple": #this block adds a response for if you have not chosen a fruit yet

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You did not choose apples or oranges.


#### Coins

In [81]:
import numpy as np #this block imported numpy and then generated a random number between 0-1
np.random.random()

0.05646298320614851

In [82]:
np.random.random() > 0.5 #this line asked if the number that was randomly generated was greater than 0.5 and it wasnt so the system printed false

False

In [83]:
def flip_coin(): #this block tells the computer that when given to command flip coin it should generate a number between 0-1 and if the number is less than 0.5 it prints tails and heads if its more than 0.5
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

In [84]:
flip_coin() #demonstration of the flip coin command

Heads


### Graphics Output

In [27]:
from IPython.core.display import display, HTML

In [85]:
display(HTML('<h1>Hello, world!</h1>')) #this command will write hello world in a text box

In [86]:
def coin(): #this block tells the system to return either a 1 or 0 when given the command "coin"
  return np.random.randint(2)

In [87]:
coin() #demonstration of the coin command

1

In [88]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">')) #this line simply displays the picture asscoiated with the link

In [89]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg' #this block designated different pictures for the variables heads and tails
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

In [33]:
def show_img(img): #this block sets a show image command that will display the image associated with a variable (either heads or tails)
  display(HTML('<img src=' + img + '>'))

In [34]:
show_img(heads) #demonstration of the show image command

In [35]:
show_img(tails) #demonstration of the show image command

In [90]:
def flip_coin(): #this block will combine the flip coin command with the show image command so that when you flip a coin it will display the image for either heads or tails

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [91]:
flip_coin() #demonstration of the new flip coin command

In [92]:
for i in range(5): #this line will flip as many coins as told in the variable, so 5 in this case
    flip_coin()

In [39]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [40]:
def shuffle(x): #i think this block will take a created set of numbers and randomly shuffle the nu8mbers in that set
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [41]:
a = np.arange(52) #this line creates a 52 number set called "a"

In [93]:
shuffle(a) #this line shuffled the "a" set previously created

array([ 3, 35,  0, 14, 16,  6, 26, 46,  7, 51,  2,  9, 38, 15, 49, 41, 29,
       17, 39,  5, 25, 34, 42, 48,  1, 19, 13, 11,  4, 23, 10, 12, 36, 21,
       47, 28, 20, 45, 27, 33, 24, 50, 44, 40, 32, 30, 37, 22,  8, 43, 31,
       18])

In [43]:
np.random.permutation(52) #i think this line created a set of numbers from 0-51 and randomized the order

array([10, 44, 42, 45, 18,  1, 27, 12, 25,  8, 48, 46, 31,  9, 28, 17, 41,
       32, 30, 49,  2, 38, 39,  4, 29, 35, 50, 20, 51,  6, 15, 37, 47, 36,
       40, 16, 21,  3, 34, 24, 19,  5, 13,  0, 14, 26, 11, 23, 22, 43,  7,
       33])

### Speed Test

In [44]:
%%timeit
shuffle(a)

188 µs ± 20.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [45]:
%%timeit
np.random.permutation(52)

3.63 µs ± 255 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [46]:
import numpy as np #imported nump commands

In [47]:
np.random.permutation(52) #i think this line created a set of numbers from 0-51 and randomized the order

array([10, 37, 31, 38,  7, 47,  0,  1, 34, 19,  4, 43, 17, 18, 50, 32, 46,
       13, 21,  3,  6, 22, 25, 27, 11, 20, 23, 35, 29,  9,  2, 28, 15, 24,
       39, 49, 14, 45, 42, 40, 48, 36, 12, 33, 44, 26,  8,  5, 30, 51, 16,
       41])

In [48]:
cards = np.random.permutation(52) #this line designated a random set of numbers 0-51 with the name "cards"

In [49]:
cards

array([ 4, 27, 36,  0, 50,  6, 26,  8, 19, 41, 46, 32, 22, 10, 25, 28, 12,
        1, 45, 13, 29,  2, 23, 31,  3, 48, 51, 34, 40, 30, 39, 43, 24,  9,
       49, 35, 15, 37, 42, 11, 14, 38, 44,  5, 21, 47, 33, 17, 20, 16, 18,
        7])

In [94]:
cards[0] #this line tells us the first number in the "cards" set is 4

47

In [51]:
cards[1] #this line tells us the second number in the "cards" set is 27

27

In [52]:
cards[2] #this line tells us the third number in the "cards" set is 36

36

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [95]:
np.arange(52).reshape(4,13) #this line designated the 52 numbers into 4 sets of 13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [96]:
np.arange(52).reshape(4,13)%13 #this line tells the computer to make all the 4 sets only be the numbers 0-12

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [97]:
np.arange(52).reshape(4,13)//13 #this line made each set 1 consist of only 1 number between 0-3

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [56]:
suits = ['Clubs','Spades','Hearts','Diamonds'] #this line told the system that there are 4 suits
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King'] #this line told the computer the names of each card in the deck

In [57]:
def card_name(card_number): #this line designated a command to generate a card, so it combines a name and a suit
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [58]:
card_name(0) #this shows the first card in the deck is the acxe of clubs

'Ace of Clubs'

In [98]:
card_name(51) #this shows the last card in the deck is the king of diamonds

'King of Diamonds'

In [60]:
cards = np.random.permutation(52) #this line shuffled the previously created deck

In [99]:
top_of_deck         = card_name(cards[0]) #this block generated new variables that return with a certain card in the deck
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [62]:
top_of_deck, second_card_in_deck, last_card_in_deck #this is a demonstration of the last block, so it shows the first card in the now shuffled deck is the nine of diamonds

('Nine of Diamonds', 'Eight of Spades', 'King of Diamonds')

In [100]:
for i in range(5): #this block tells the system to give the first 5 cards in the shuffled deck
    print(card_name(cards[i]))

Nine of Diamonds
Eight of Spades
Three of Hearts
King of Spades
Five of Hearts


In [64]:
for i in range(15): #this block tells the system to give the first 15 cards in the shuffled deck
    print(card_name(cards[i]))

Nine of Diamonds
Eight of Spades
Three of Hearts
King of Spades
Five of Hearts
Five of Spades
Nine of Clubs
Jack of Spades
King of Clubs
Three of Diamonds
Four of Spades
Queen of Hearts
Four of Clubs
Six of Diamonds
Ace of Clubs


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [65]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [101]:
suit = ['k','p','s','l'] #this block changed the list of suits and card names to abbreviations
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [67]:
i = np.random.randint(4) #this line designates command i to return the command with a number from 0-3
j = np.random.randint(13) #this line designates command j to return the command with a number from 0-12

In [68]:
i,j #demonstrates the 2 last commands

(0, 5)

In [69]:
suit[i] 

'k'

In [70]:
card[j]

'6'

In [71]:
from IPython.core.display import display, HTML

In [102]:
def show_img(img): #this block tells the computer to display an image when given the show img command
  display(HTML('<img src=' + img + '>'))

In [73]:
img = card_url_head + suit[i] + card[j] + card_url_tail #this line tells the computer what image to show when given the img command

In [105]:
show_img(img) #demonstration of the show img command

In [106]:
def card_image(card_number): #i think this line tells the computer to generate an image for a random card in the deck
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [107]:
card_image(3) #demonstration of the last command

'k4'

In [77]:
img = card_url_head + card_image(3) + card_url_tail

In [78]:
show_img(img)

In [108]:
for i in range(52): #this block will generate an image for each card in the deck
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)